version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: src/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app
    environment:
      - SQLALCHEMY_DATABASE_URL=sqlite:///./src/UNI.db

